version: '4.13'

services:
  backend:
    build: .
    container_name: backend-todo
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - ./core:/app
    ports:
      - "8001:8001"
    environment:
      - SECRET_KEY=test
      - DEBUG=True